
package tf_poo_gr6_2021_03_NA_gui;

import tf_poo_gr6_2021_03_NA_modelo.Punto;
import tf_poo_gr6_2021_03_NA_modelo.J;

/**
 *
 * Tarea Final de Programación Orientada a Objetos.
 * Cali, octubre 27 de 2021.
 * @author Prof. J. Antonio LemOs B.
 * 
 */

public class Regresiones_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Regresiones_GUI
     */
    public Regresiones_GUI() {
        initComponents();
    }
    
    // Método interno que crea un punto de la muestra y retorna su referencia:  
    private Punto crearPunto() {
        // Variables locales:
        Punto pto = null;
        double x;  // Abscisa (o primera coordenada) del punto.
        double y;  // Ordenada (o segunda coordenada) del punto.
        x = J.leerReal("Digite la abscisa (o primera coordenada) del punto: ");
        y = J.leerReal("Digite la ordenada (o segunda coordenada) del punto: ");
        pto = new Punto(x, y);
        return  pto;        
    }   // Punto crearPunto()
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tarea Final POO 2021-01");
        setBackground(new java.awt.Color(204, 204, 204));
        setFont(new java.awt.Font("Agency FB", 1, 12)); // NOI18N
        setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 941, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 564, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("Convert2Lambda")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Regresiones_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Regresiones_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Regresiones_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Regresiones_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Regresiones_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}